# -*- coding: utf-8 -*-
"""Verify a connector model generated by connector_generator.py."""

import argparse
import os

import FreeCAD as App
import Part


TOLERANCE = 0.03


def assert_close(actual, expected, label, tolerance=TOLERANCE):
    if abs(float(actual) - float(expected)) > tolerance:
        raise AssertionError(
            "%s: expected %.3f, got %.3f" % (label, float(expected), float(actual))
        )


def verify_model(fcstd_path, step_path=None):
    fcstd_path = os.path.abspath(fcstd_path)
    step_path = os.path.abspath(step_path or os.path.splitext(fcstd_path)[0] + ".step")
    if not os.path.isfile(fcstd_path):
        raise AssertionError("FCStd file missing: %s" % fcstd_path)
    if not os.path.isfile(step_path):
        raise AssertionError("STEP file missing: %s" % step_path)

    doc = App.openDocument(fcstd_path)
    params = doc.getObject("Parameters")
    if params is None or params.BuildId != "CONNECTOR_GENERATOR_V1":
        raise AssertionError("model was not produced by the generic connector generator")

    poles = int(params.Poles)
    pitch = float(params.Pitch)
    cover_width = float(params.CoverWidth)
    expected_parts = poles * 4 + 1
    housings = [doc.getObject("Housing_P%d" % index) for index in range(1, poles + 1)]
    actuators = [doc.getObject("Actuator_P%d" % index) for index in range(1, poles + 1)]
    pins = [
        doc.getObject("Pin_P%d_%s" % (index, suffix))
        for index in range(1, poles + 1)
        for suffix in ("A", "B")
    ]
    cover = doc.getObject("SideCover")
    parts = housings + actuators + pins + [cover]
    if any(obj is None for obj in parts):
        raise AssertionError("assembly is missing generated component objects")
    if len(parts) != expected_parts:
        raise AssertionError("expected %d parts, got %d" % (expected_parts, len(parts)))
    for obj in parts:
        if obj.Shape.isNull() or not obj.Shape.isValid() or obj.Shape.Volume <= 0:
            raise AssertionError("invalid component geometry: %s" % obj.Name)

    for index, housing in enumerate(housings):
        assert_close(housing.Shape.BoundBox.XLength, pitch, "housing width")
        assert_close(housing.Shape.BoundBox.Center.x, pitch * (index + 0.5), "pole center")
        if housing.ConfiguredColor != params.BodyColor:
            raise AssertionError("housing color mismatch: %s" % housing.Name)
    assert_close(cover.Shape.BoundBox.XLength, cover_width, "cover width")
    assert_close(cover.Shape.BoundBox.XMin, poles * pitch, "cover start")
    if cover.ConfiguredColor != params.BodyColor:
        raise AssertionError("side cover color mismatch")

    actuator_colors = list(params.ActuatorColors)
    if len(actuator_colors) != poles:
        raise AssertionError("actuator color metadata count mismatch")
    for index, actuator in enumerate(actuators):
        if actuator.ConfiguredColor != actuator_colors[index]:
            raise AssertionError("actuator color mismatch: %s" % actuator.Name)
    for pin in pins:
        if pin.ConfiguredColor != params.TerminalPinColor:
            raise AssertionError("terminal pin color mismatch: %s" % pin.Name)

    body = Part.makeCompound([obj.Shape for obj in housings + [cover]])
    assert_close(body.BoundBox.XLength, poles * pitch + cover_width, "overall width")
    assert_close(body.BoundBox.YLength, float(params.Depth), "body depth")
    assert_close(body.BoundBox.ZLength, float(params.BodyHeight), "body height")
    App.closeDocument(doc.Name)

    step_doc = App.newDocument("StepVerification")
    Part.insert(step_path, step_doc.Name)
    step_doc.recompute()
    step_objects = [
        obj
        for obj in step_doc.Objects
        if hasattr(obj, "Shape") and not obj.Shape.isNull() and obj.Shape.Volume > 0
    ]
    solid_count = sum(len(obj.Shape.Solids) for obj in step_objects)
    if solid_count != expected_parts:
        raise AssertionError(
            "STEP expected %d solids, got %d" % (expected_parts, solid_count)
        )
    App.closeDocument(step_doc.Name)
    result = {
        "poles": poles,
        "parts": expected_parts,
        "width": poles * pitch + cover_width,
        "fcstd": fcstd_path,
        "step": step_path,
    }
    print(
        "VERIFY_OK poles=%d parts=%d width=%.3f FCSTD=%s STEP=%s"
        % (poles, expected_parts, result["width"], fcstd_path, step_path)
    )
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fcstd")
    parser.add_argument("--step")
    args = parser.parse_args(argv)
    verify_model(args.fcstd, args.step)


if __name__ == "__main__":
    main()

