# -*- coding: utf-8 -*-
"""Acceptance checks for the script-built DA803 3P assembly."""

import os
import sys

import FreeCAD as App
import Part


BASE_DIR = os.environ.get(
    "DA803_DIR",
    os.path.dirname(os.path.abspath(globals().get("__file__", os.getcwd()))),
)
FCSTD_PATH = os.path.join(BASE_DIR, "DA803-350-3P.FCStd")
STEP_PATH = os.path.join(BASE_DIR, "DA803-350-3P.step")
TOL = 0.03


def close_all_documents():
    for name in list(App.listDocuments().keys()):
        App.closeDocument(name)


def assert_close(actual, expected, label, tolerance=TOL):
    if abs(actual - expected) > tolerance:
        raise AssertionError(
            "%s: expected %.3f, got %.3f" % (label, expected, actual)
        )


def shape_objects(doc):
    return [
        obj
        for obj in doc.Objects
        if hasattr(obj, "Shape") and not obj.Shape.isNull() and obj.Shape.Volume > 0
    ]


def verify_fcstd():
    if not os.path.isfile(FCSTD_PATH):
        raise AssertionError("FCStd output is missing: %s" % FCSTD_PATH)

    doc = App.openDocument(FCSTD_PATH)
    params = doc.getObject("Parameters")
    if params is None or getattr(params, "BuildId", "") != "DA803_SCRIPTED_3P_V2":
        raise AssertionError("FCStd was not generated by the DA803 scripted builder")

    housings = [doc.getObject("Housing_P%d" % i) for i in range(1, 4)]
    cover = doc.getObject("SideCover")
    levers = [doc.getObject("Lever_P%d" % i) for i in range(1, 4)]
    pins = [
        doc.getObject("Pin_P%d_%s" % (i, suffix))
        for i in range(1, 4)
        for suffix in ("A", "B")
    ]
    if any(obj is None for obj in housings + [cover] + levers + pins):
        raise AssertionError("Assembly tree is missing expected component objects")

    parts = housings + [cover] + levers + pins
    for obj in parts:
        if not obj.Shape.isValid() or obj.Shape.Volume <= 0:
            raise AssertionError("Invalid or empty shape: %s" % obj.Name)

    for index, housing in enumerate(housings, 1):
        assert_close(housing.Shape.BoundBox.XLength, 3.5, "housing P%d width" % index)
    assert_close(cover.Shape.BoundBox.XLength, 1.5, "side cover width")

    expected_centers = (1.75, 5.25, 8.75)
    actual_centers = [obj.Shape.BoundBox.Center.x for obj in housings]
    for index, (actual, expected) in enumerate(zip(actual_centers, expected_centers), 1):
        assert_close(actual, expected, "housing P%d center" % index)
    assert_close(cover.Shape.BoundBox.XMin, 10.5, "side cover start")
    assert_close(cover.Shape.BoundBox.XMax, 12.0, "side cover end")

    if getattr(params, "LeverHingeSide", "") != "Rear":
        raise AssertionError("Lever hinge must be on the rear side")
    if getattr(params, "LeverState", "") != "Closed":
        raise AssertionError("Default lever state must be Closed")
    if getattr(params, "BodyColor", "") != "#8C8C8C":
        raise AssertionError("Default body color must be #8C8C8C")
    if getattr(params, "LeverColor", "") != "#202020":
        raise AssertionError("Default lever color must be #202020")

    body = Part.makeCompound([obj.Shape for obj in housings + [cover]])
    complete = Part.makeCompound([obj.Shape for obj in parts])
    bb_body = body.BoundBox
    bb_all = complete.BoundBox
    assert_close(bb_body.XLength, 12.0, "body width")
    assert_close(bb_body.YLength, 12.5, "body depth")
    assert_close(bb_body.ZLength, 10.6, "body height")
    assert_close(bb_all.ZMin, -3.5, "pin bottom")
    if bb_all.ZMax > 11.8:
        raise AssertionError("Closed levers are unexpectedly high: %.3f" % bb_all.ZMax)

    centers = [doc.getObject("Pin_P%d_A" % i).Shape.BoundBox.Center.x for i in range(1, 4)]
    assert_close(centers[0], 1.75, "first pole center")
    assert_close(centers[1] - centers[0], 3.5, "pole pitch 1-2")
    assert_close(centers[2] - centers[1], 3.5, "pole pitch 2-3")
    y_a = doc.getObject("Pin_P1_A").Shape.BoundBox.Center.y
    y_b = doc.getObject("Pin_P1_B").Shape.BoundBox.Center.y
    assert_close(abs(y_b - y_a), 5.0, "pin row pitch")

    print(
        "FCSTD_OK parts=%d body=%.3fx%.3fx%.3f all_z=[%.3f,%.3f]"
        % (
            len(parts),
            bb_body.XLength,
            bb_body.YLength,
            bb_body.ZLength,
            bb_all.ZMin,
            bb_all.ZMax,
        )
    )
    App.closeDocument(doc.Name)


def verify_step():
    if not os.path.isfile(STEP_PATH):
        raise AssertionError("STEP output is missing: %s" % STEP_PATH)

    doc = App.newDocument("StepVerification")
    Part.insert(STEP_PATH, doc.Name)
    doc.recompute()
    objects = shape_objects(doc)
    solid_count = sum(len(obj.Shape.Solids) for obj in objects)
    if solid_count != 13:
        raise AssertionError("STEP expected 13 solids, got %d" % solid_count)
    for obj in objects:
        if not obj.Shape.isValid():
            raise AssertionError("STEP contains invalid geometry: %s" % obj.Name)
    print("STEP_OK objects=%d solids=%d" % (len(objects), solid_count))
    App.closeDocument(doc.Name)


def main():
    close_all_documents()
    verify_fcstd()
    verify_step()
    print("VERIFY_OK")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print("VERIFY_FAILED: %s" % exc)
        close_all_documents()
        sys.stdout.flush()
        raise
